apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-consumer"
  labels:
    app: "{{ .Release.Name }}-consumer"
    app.kubernetes.io/name: "{{ .Release.Name }}-consumer"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.consumer.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-consumer"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-consumer"
    spec:
      containers:
      - name: consumer
        image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
        imagePullPolicy: "{{ .Values.consumer.image.pullPolicy }}"
        resources:
          limits:
            cpu: "{{ .Values.consumer.resources.limits.cpu }}"
            memory: "{{ .Values.consumer.resources.limits.memory }}"
        env:
        - name: CONSUMER_ID
          value: "{{ .Values.consumer.env.CONSUMER_ID }}"
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-configmap" 