apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: "{{ .Release.Name }}-elasticsearch"
  labels:
    app: "{{ .Release.Name }}-elasticsearch"
    app.kubernetes.io/name: "{{ .Release.Name }}-elasticsearch"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  version: "{{ .Values.elasticsearch.version }}"
  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.replicas }}
    config:
      node.store.allow_mmap: false
      node.roles: ["master", "data", "ingest"]
      xpack.security.enabled: {{ .Values.elasticsearch.security.enabled }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: "{{ .Values.elasticsearch.resources.limits.cpu }}"
              memory: "{{ .Values.elasticsearch.resources.limits.memory }}"
            {{- if .Values.elasticsearch.resources.requests }}
            requests:
              {{- if .Values.elasticsearch.resources.requests.cpu }}
              cpu: "{{ .Values.elasticsearch.resources.requests.cpu }}"
              {{- end }}
              {{- if .Values.elasticsearch.resources.requests.memory }}
              memory: "{{ .Values.elasticsearch.resources.requests.memory }}"
              {{- end }}
            {{- end }}
          env:
          - name: ES_JAVA_OPTS
            value: "{{ .Values.elasticsearch.env.ES_JAVA_OPTS }}"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: "{{ include "synthgen.storageClass" . }}"
        resources:
          requests:
            storage: "{{ .Values.elasticsearch.persistence.size }}"
---
# Service to expose Elasticsearch HTTP API
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-elasticsearch-http"
  labels:
    app: "{{ .Release.Name }}-elasticsearch"
    app.kubernetes.io/name: "{{ .Release.Name }}-elasticsearch"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "{{ .Values.elasticsearch.service.type }}"
  ports:
  - port: {{ .Values.elasticsearch.service.port }}
    targetPort: 9200
    protocol: TCP
    name: http
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: "{{ .Release.Name }}-elasticsearch"