apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  API_SECRET_KEY: {{ .Values.api.env.API_SECRET_KEY | b64enc }} 