services:
  rabbitmq:
    image: rabbitmq:4.0-management
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - synthetic-data-network

  postgres:
    image: postgres:17.2
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synthetic_data
      - POSTGRES_MAX_CONNECTIONS=1000
      - POSTGRES_SHARED_BUFFERS=1024MB   
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - synthetic-data-network

  api:
    build: .
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    container_name: synthetic-data-api
    ports:
      - "8002:8000"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synthetic_data
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432   
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src 
    networks:
      - synthetic-data-network

  consumer:
    build: 
      context: .
      dockerfile: Dockerfile.consumer
    deploy:
      mode: replicated
      replicas: ${NUM_CONSUMERS:-1}
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synthetic_data
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CONSUMER_ID=${CONSUMER_ID:-1}
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    env_file:
      - ./src/.env
    networks:
      - synthetic-data-network

volumes:
  postgres_data: 

# Add networks configuration at the bottom of the file
networks:
  synthetic-data-network:
    driver: bridge 