model_list:
  - model_name: gemini-2.0-flash-001
    litellm_params:
      model: gemini/gemini-2.0-flash-001
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash-lite
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-thinking-exp-01-21
    litellm_params:
      model: gemini/gemini-2.0-flash-thinking-exp-01-21
      api_key: os.environ/GEMINI_API_KEY
  - model_name: Llama-3.3-70B-Instruct
    litellm_params:
      model: huggingface/meta-llama/Llama-3.3-70B-Instruct
      api_key: os.environ/HUGGINGFACE_API_KEY