[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "synthetic-data-generator"
version = "1.0.0"
description = "Synthetic Data Generator using LLMs"
requires-python = ">=3.8" 