global:
  environment: production
  imagePullSecrets: []
  storageClass: standard

# RabbitMQ configuration
rabbitmq:
  image:
    repository: rabbitmq
    tag: 4.0-management
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  service:
    type: ClusterIP
    port: 5672
    managementPort: 15672
  persistence:
    enabled: true
    size: 8Gi
  env:
    RABBITMQ_USER: guest
    RABBITMQ_PASS: guest
    RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 3600000

# UI configuration
ui:
  image:
    repository: nasirus/synthgen-ui
    tag: 0.0.11
    pullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  service:
    type: NodePort
    port: 3000
    nodePort: 30080
  env:
    API_URL: http://synthgen-api
    API_PORT: 8000
    API_SECRET_KEY: sk1-1564813548

# API configuration
api:
  replicas: 1
  image:
    repository: nasirus/synthgen-api
    tag: 0.0.11
    pullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  service:
    type: NodePort
    port: 8000
    nodePort: 30081
  env:
    API_PORT: 8000
    API_SECRET_KEY: sk1-1564813548

# Consumer configuration
consumer:
  replicas: 1
  image:
    repository: nasirus/synthgen-consumer
    tag: 0.0.11
    pullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  env:
    MAX_PARALLEL_TASKS: 10

# Minio configuration
minio:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2025-02-07T23-21-09Z
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: ClusterIP
    apiPort: 9000
    consolePort: 9001
  persistence:
    enabled: true
    size: 10Gi
  env:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MINIO_BUCKET_NAME: synthetic-data-generator

# Worker configuration
worker:
  replicas: 1
  image:
    repository: nasirus/synthgen-worker
    tag: 0.0.11
    pullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"

# Elasticsearch configuration
elasticsearch:
  version: 8.17.3
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: ClusterIP
    port: 9200
  persistence:
    enabled: true
    size: 10Gi
  env:
    ES_JAVA_OPTS: -Xms256m -Xmx256m
  security:
    enabled: false

# LiteLLM configuration
litellm:
  image:
    repository: ghcr.io/berriai/litellm
    tag: main-latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
  service:
    type: ClusterIP
    port: 4000

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: synthgen.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: synthgen-ui
          servicePort: 3000
        - path: /api
          pathType: Prefix
          serviceName: synthgen-api
          servicePort: 8000
  tls: [] 