name: Deploy Docker Images

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      # Build and push API image
      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/synthgen-api:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/synthgen-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-api:buildcache,mode=max

      # Build and push Consumer image
      - name: Build and push Consumer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.consumer
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/synthgen-consumer:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/synthgen-consumer:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-consumer:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-consumer:buildcache,mode=max

      # Build and push Worker image
      - name: Build and push Worker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.worker
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/synthgen-worker:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/synthgen-worker:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-worker:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-worker:buildcache,mode=max

      - name: Build and push UI image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.ui
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/synthgen-ui:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/synthgen-ui:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-ui:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/synthgen-ui:buildcache,mode=max
